UPDATE board SET use_board = 'T',is_display_main = 'F',left_right = ' ',top_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/board_top.gif',top_image_map = '',is_menu_image = ' ',menu_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_04.gif',is_menu_rollover = '/',menu_rollover_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_04_over.gif',is_title_image = 'F',title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/title/top_t_board04.gif',is_home_title_image = 'F',home_title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/home_tle_04.gif',is_top_image_map = 'F',is_deleted = 'F'WHERE board_no = '4';
UPDATE board SET use_board = 'F',is_display_main = 'T',left_right = 'L',top_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/board_top.gif',top_image_map = '',is_menu_image = ' ',menu_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_02.gif',is_menu_rollover = '/',menu_rollover_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_02_over.gif',is_title_image = 'F',title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/title/top_t_board02.gif',is_home_title_image = 'F',home_title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/home_tle_02.gif',is_top_image_map = 'F',is_deleted = 'F'WHERE board_no = '2';
UPDATE board SET use_board = 'T',is_display_main = 'T',left_right = 'R',top_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/board_top.gif',top_image_map = '',is_menu_image = ' ',menu_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_05.gif',is_menu_rollover = '/',menu_rollover_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_05_over.gif',is_title_image = 'F',title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/title/top_t_board05.gif',is_home_title_image = 'F',home_title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/home_tle_05.gif',is_top_image_map = 'F',is_deleted = 'F'WHERE board_no = '6';
UPDATE board SET use_board = 'T',is_display_main = 'T',left_right = 'T',top_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/board_top.gif',top_image_map = 'M',is_menu_image = ' ',menu_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_01.gif',is_menu_rollover = '/',menu_rollover_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_01_over.gif',is_title_image = 'F',title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/title/top_t_board01.gif',is_home_title_image = 'F',home_title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/home_tle_01.gif',is_top_image_map = 'F',is_deleted = 'F'WHERE board_no = '1';
UPDATE board SET use_board = 'F',is_display_main = 'F',left_right = ' ',top_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/board_top.gif',top_image_map = '',is_menu_image = ' ',menu_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_03.gif',is_menu_rollover = '/',menu_rollover_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_03_over.gif',is_title_image = 'F',title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/title/top_t_board03.gif',is_home_title_image = 'F',home_title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/home_tle_03.gif',is_top_image_map = 'F',is_deleted = 'F'WHERE board_no = '3';
UPDATE board SET use_board = 'F',is_display_main = 'F',left_right = ' ',top_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/admindiary/top_01.gif',top_image_map = '',is_menu_image = ' ',menu_image = '',is_menu_rollover = '/',menu_rollover_image = '',is_title_image = 'F',title_image = '',is_home_title_image = 'F',home_title_image = '',is_top_image_map = 'F',is_deleted = 'F'WHERE board_no = '11';
UPDATE board SET use_board = 'F',is_display_main = 'T',left_right = ' ',top_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/board_top.gif',top_image_map = '',is_menu_image = ' ',menu_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_05.gif',is_menu_rollover = '/',menu_rollover_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_05_over.gif',is_title_image = 'F',title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/title/top_t_board05.gif',is_home_title_image = 'F',home_title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/home_tle_05.gif',is_top_image_map = 'F',is_deleted = 'F'WHERE board_no = '101';
UPDATE board SET use_board = 'F',is_display_main = 'F',left_right = ' ',top_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/myshop/top_01.gif',top_image_map = '',is_menu_image = ' ',menu_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/myshop/1_1_off.gif',is_menu_rollover = '/',menu_rollover_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/myshop/1_1_on.gif',is_title_image = 'F',title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/title/top_t_board04.gif',is_home_title_image = 'F',home_title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/home_tle_04.gif',is_top_image_map = 'F',is_deleted = 'F'WHERE board_no = '9';
UPDATE board SET use_board = 'T',is_display_main = 'F',left_right = ' ',top_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/myshop/top_01.gif',top_image_map = '',is_menu_image = 'F',menu_image = '',is_menu_rollover = 'F',menu_rollover_image = '',is_title_image = 'F',title_image = '',is_home_title_image = 'F',home_title_image = '',is_top_image_map = 'F',is_deleted = 'F'WHERE board_no = '10';
UPDATE board SET use_board = 'F',is_display_main = 'F',left_right = ' ',top_image = '',top_image_map = '',is_menu_image = 'F',menu_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/myshop/left_m_07.gif',is_menu_rollover = 'F',menu_rollover_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/myshop/left_m_07_over.gif',is_title_image = 'F',title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/title/top_t_board_memo.gif',is_home_title_image = 'F',home_title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/home_tle_10.gif',is_top_image_map = 'F',is_deleted = 'F'WHERE board_no = '1001';
UPDATE board SET use_board = 'F',is_display_main = 'F',left_right = ' ',top_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/board_top.gif',top_image_map = '',is_menu_image = ' ',menu_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_07.gif',is_menu_rollover = '/',menu_rollover_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_07_over.gif',is_title_image = 'F',title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/title/top_t_board07.gif',is_home_title_image = 'F',home_title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/home_tle_07.gif',is_top_image_map = 'F',is_deleted = 'F'WHERE board_no = '7';
UPDATE board SET use_board = 'F',is_display_main = 'F',left_right = ' ',top_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/board_top.gif',top_image_map = '',is_menu_image = ' ',menu_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_06.gif',is_menu_rollover = '/',menu_rollover_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_06_over.gif',is_title_image = 'F',title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/title/top_t_board06.gif',is_home_title_image = 'F',home_title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/home_tle_06.gif',is_top_image_map = 'F',is_deleted = 'F'WHERE board_no = '5';
UPDATE board SET use_board = 'T',is_display_main = 'F',left_right = ' ',top_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/g_board_top.gif',top_image_map = '',is_menu_image = 'F',menu_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_08.gif',is_menu_rollover = 'F',menu_rollover_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_08_over.gif',is_title_image = 'F',title_image = '',is_home_title_image = 'F',home_title_image = '',is_top_image_map = 'F',is_deleted = 'F'WHERE board_no = '8';
UPDATE board SET use_board = 'F',is_display_main = 'F',left_right = ' ',top_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/board_top.gif',top_image_map = '',is_menu_image = ' ',menu_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_06.gif',is_menu_rollover = '/',menu_rollover_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/left_m_06_over.gif',is_title_image = 'F',title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/title/top_t_board06.gif',is_home_title_image = 'F',home_title_image = 'http://img0001.echosting.cafe24.com/front/type_b/image/board/home_tle_06.gif',is_top_image_map = 'F',is_deleted = 'F'WHERE board_no = '1002';
UPDATE mall_run_type SET new_bbs = 'T';


UPDATE category SET use_image = 'F' WHERE is_main = 'T';
UPDATE estimate_config SET use_image = 'T',category_image = 'online.gif',category_image_over = '',use_b_image = ' ',banner_image = '',use_top_image_map = ' ',top_image_map = '',use_top_image = 'T',top_image = 'online_top.gif';
